version: "3"
volumes:
  data:
services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mariadb
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
      - ./userdatas.sql:/docker-entrypoint-initdb.d/userdatas.sql
    ports:
      - "3306:3306"
  nginx:
    image: nginx
    ports:
      - "9091:9091"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/services.conf:/etc/nginx/sites-available/services.conf
    depends_on:
      - app
